apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: garvbahal/gitops-codebase:5e923c5fad9f899a05d4acc3cc2865057abd908b
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: 128Mi
            limits:
              cpu: "800m"
              memory: 512Mi
