apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-main

resources:
  - ../../base

replicas:
  - name: backend-deployment
    count: 4

images:
  - name: garvbahal/gitops-codebase
    newTag: 0c8e4648910dea73c377c67bc8f6e4a66bb1baeb
