apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-main

resources:
  - ../../base

replicas:
  - name: backend-deployment
    count: 4

images:
  - name: garvbahal/gitops-codebase
    newTag: 1dfc3fd192d875ae3240b29c036b7b458e62c8ba
